[package]
name = "vocab-api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", features = ["sqlx_macros", "sqlx_sqlite"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
